apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: staticManagedVolumeRetain
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
reclaimPolicy: Retain
